#!/usr/bin/env bash
# sdd app management file for dbeaver DB management GUI

SOFTWARE_DIR=~/software

sdd_install() {
    local version archive
    version=$1

    archive=dbeaver-ce-"$version"-linux.gtk.x86_64.tar.gz
    wget -P /tmp https://dbeaver.io/files/"$version"/"$archive"

    cd /tmp || return 1
    tar xfv "$archive"

    mkdir -p $SOFTWARE_DIR
    rm -rfv $SOFTWARE_DIR/dbeaver
    mv -v dbeaver $SOFTWARE_DIR

    ln -s $SOFTWARE_DIR/dbeaver/dbeaver "$SDD_INSTALL_PREFIX"/bin/dbeaver
    rm /tmp/"$archive"
}

sdd_uninstall() {
    rm -rfv $SOFTWARE_DIR/dbeaver
    rm -rfv "$SDD_INSTALL_PREFIX"/bin/dbeaver
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release dbeaver dbeaver
}
