#!/usr/bin/env bash

sdd_install() {
    cd /tmp || return 1
    git clone https://github.com/pylipp/dzr
    cd dzr || return 1
    git checkout fca867b0adb78b9cc9de239a324f12f293e401f0
    cp -v dzr dzr-url dzr-dec "$SDD_INSTALL_PREFIX"/bin
    cd ..
    rm -rfv dzr
}

sdd_uninstall() {
    rm -fv "$SDD_INSTALL_PREFIX"/bin/dzr
    rm -fv "$SDD_INSTALL_PREFIX"/bin/dzr-dec
    rm -fv "$SDD_INSTALL_PREFIX"/bin/dzr-url
}

sdd_fetch_latest_version() {
    _sha_of_github_master pylipp dzr
}
