#!/usr/bin/env bash

sdd_install() {
    cd /tmp || return 1
    git clone https://github.com/pylipp/dzr
    cp -v dzr/dzr dzr/dzr-url dzr/dzr-dec "$SDD_INSTALL_PREFIX"/bin
    rm -rfv dzr
}

sdd_uninstall() {
    rm -fv "$SDD_INSTALL_PREFIX"/bin/dzr
    rm -fv "$SDD_INSTALL_PREFIX"/bin/dzr-dec
    rm -fv "$SDD_INSTALL_PREFIX"/bin/dzr-url
}

sdd_fetch_latest_version() {
    _sha_of_github_master pylipp dzr
}
