#!/bin/bash

sdd_install() {
    rm -f ~/.zshrc ~/.zshrc.pre-oh-my-zsh
    ln -s ~/.files/zshrc ~/.zshrc

    # Attempt to change login shell; fallback to launching zsh when bash is launched
    if [[ $SHELL != *zsh ]]; then
        chsh -s $(which zsh) || echo exec zsh >> ~/.bashrc
    fi
}

sdd_uninstall() {
    rm -f ~/.zshrc
    sed -i 's/exec zsh//g' ~/.bashrc
}
