#!/bin/bash

tmux_version=2.6
libevent_version=2.0.21
ncurses_version=5.9

tmux_name="tmux-$tmux_version"
libevent_name="libevent-$libevent_version-stable"
ncurses_name="ncurses-$ncurses_version"

target_dir=${SDD_INSTALL_PREFIX:-"$HOME/.local"}
tmux_conf=~/.tmux.conf

sdd_install() {
    # Shamelessly borrowed from https://gist.github.com/ryin/3106801

    # Assert presence of compilation programs
    command -v make || return 1
    command -v gcc || return 1
    command -v g++ || return 1

    # download source files for tmux, libevent, and ncurses
    cd /tmp

    wget -O $tmux_name.tar.gz https://github.com/tmux/tmux/releases/download/${tmux_version}/${tmux_name}.tar.gz
    wget -O $libevent_name.tar.gz https://github.com/downloads/libevent/libevent/$libevent_name.tar.gz
    wget -O $ncurses_name.tar.gz ftp://ftp.gnu.org/gnu/ncurses/$ncurses_name.tar.gz

    # extract files, configure, and compile

    # libevent installation
    tar xvzf $libevent_name.tar.gz
    cd $libevent_name
    ./configure --prefix=$target_dir --disable-shared
    make
    make install
    cd -

    # ncurses installation
    tar xvzf $ncurses_name.tar.gz
    cd $ncurses_name
    CPPFLAGS=-P ./configure --prefix=$target_dir
    make
    make install
    cd -

    # tmux installation
    tar xvzf ${tmux_name}*.tar.gz
    cd ${tmux_name}*/
    ./configure CFLAGS="-I$target_dir/include -I$target_dir/include/ncurses" LDFLAGS="-L$target_dir/lib -L$target_dir/include/ncurses -L$target_dir/include"
    CPPFLAGS="-I$target_dir/include -I$target_dir/include/ncurses" LDFLAGS="-static -L$target_dir/include -L$target_dir/include/ncurses -L$target_dir/lib" make
    cp tmux $target_dir/bin
    cd -

    if ! $target_dir/bin/tmux -V; then
        return 1
    fi

    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

    # set up config files for plugin installation
    rm -f $tmux_conf
    ln -s ~/.files/tmux.conf $tmux_conf

    # install plugins
    cd ~/.tmux/plugins/tpm
    git checkout 26d9ace
    bin/install_plugins
}

sdd_uninstall() {
    rm -rf "$target_dir/bin/tmux" $tmux_conf ~/.tmux/plugins/tpm
}

sdd_fetch_latest_version() {
    echo $tmux_version
}
