#!/bin/bash

sdd_install() {
    set -ev
    git clone http://github.com/pylipp/virtualenvwrapper /tmp/virtualenvwrapper
    cd /tmp/virtualenvwrapper
    git checkout use-venv-module

    # Bootstrap virtualenvwrapper module
    python3 -m venv "$WORKON_HOME"/virtualenvwrapper
    . "$WORKON_HOME"/virtualenvwrapper/bin/activate
    pip install -U pip

    # Pull as little dependencies as possible
    pip install --no-deps .
    pip install stevedore
}

sdd_uninstall() {
    rm -rfv /tmp/virtualenvwrapper
    rm -rfv "$WORKON_HOME"/virtualenvwrapper
}

sdd_fetch_latest_version() {
    _name_of_latest_github_tag pylipp virtualenvwrapper
}
