#!/usr/bin/env bash

# Script to lock screen with pixelated screenshot
# inspired by i3lock-fancy
# dependencies: scrot, imagemagick, i3lock

set -e

# take screenshot
# uses xwd from x11-apps if scrot not available, see https://askubuntu.com/a/501984
image=$(mktemp).png
scrot $image || ( xwd -root -display $DISPLAY | convert - $image )

# pixelate the screenshot
convert -scale 5% -scale 2000% $image $image

# lock screen
i3lock -i $image
