#!/usr/bin/env bash

# setxkbmap resets the keyboard layout if the keyboard is un/replugged
# This script periodically checks the layout and updates it if necessary

if [[ $(pgrep -f "$0" | grep -c -v $$) -gt 1 ]]; then
    # abort if another process already running
    exit 1
fi

KBMAP_FILEPATH=/usr/share/X11/xkb/symbols/pylipp
if [[ ! -e $KBMAP_FILEPATH ]]; then
    echo "$KBMAP_FILEPATH does not exist."
    exit 1
fi

while true; do
    if [[ "$(setxkbmap -query | grep layout | awk '{ print $2; }')" != "pylipp" ]]; then
        setxkbmap pylipp -option caps:escape
    fi

    sleep 5
done
