#!/usr/bin/env bash

# Wrapper around pactl to control audio

set -e

# find running sink
sink="Master"

# get command line arguments
operation=${1:-lower}
delta=${2:-5}

# apply operation
# https://unix.stackexchange.com/a/32209/192726
if [[ $operation = "lower" ]]; then
    amixer -q sset $sink $delta%-
elif [[ $operation = "raise" ]]; then
    amixer -q sset $sink $delta%+
elif [[ $operation = "mute" ]]; then
    amixer -q sset $sink toggle
else
    echo "Usage: ./$(basename "$0") [lower|raise|mute] [delta]" >&2
    exit 1
fi
