#!/usr/bin/env bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

_collect_versions() {
    _print() {
        local program option
        program="$1"
        option="$2"

        # Abort if not installed
        command -v "$program" >/dev/null 2>&1 || return

        printf "%s\n" "$program"
        "$program" "$option"
        printf "\n"
    }

    for program in arandr bash borg cmake ctags curl dunst feh g++ gawk gcc git htop i3 i3lock make mpv nmcli node npm pulseaudio python3 scrot tig vim wget xss-lock zathura zip zsh;
    do
        _print $program --version
    done
    for program in convert latexmk xclip; do
        _print $program -version
    done
    _print sxiv -v
    _print tmux -V

    # XServer version; using `Xorg -version` shows
    #   /usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server
    head /var/log/Xorg.0.log | sed 's/^\[.*\] //'
}

main() {
    local host_dir
    host_dir="$SCRIPTDIR"/"$(hostname)"
    mkdir -p "$host_dir"

    echo "Recording apps installed on $(hostname)..."

    echo ""
    sdd list --installed | tee "$host_dir"/sdd.txt
    # Trim trailing whitespace to avoid git complaining
    sed -i 's/ *$//g' "$host_dir"/sdd.txt

    echo ""
    pipx --version > "$host_dir"/pipx.txt
    pipx list | tee -a "$host_dir"/pipx.txt

    echo ""
    yarn global list | tee "$host_dir"/yarn.txt

    echo ""
    npm list --global --parseable | tee "$host_dir"/npm.json

    echo ""
    vim +PlugClean +qa < /dev/tty
    vim "+PlugSnapshot! $host_dir/vim.txt" +qa < /dev/tty

    echo ""
    while IFS= read -r repo; do
        ( printf "%s: " "$(basename "$repo")"; cd "$repo"; git rev-parse HEAD; )
    done < <(find ~/.tmux/plugins/ -maxdepth 1 -mindepth 1 -type d) > "$host_dir"/tmux.txt

    echo ""
    _collect_versions > "$host_dir"/programs.txt 2>&1

    echo ""
    git diff -- "$SCRIPTDIR"
}

main
